defaults: &defaults
  docker:
    - image: circleci/node:12.2.0
  environment:
    CC_TEST_REPORTER_ID: 39ff6fab79be04ad2f3f4fe6d57d7665c761a8c0875f5f38c27624ed60ae3a22
  working_directory: ~/repo

version: 2

jobs:
  setup:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: Add known_hosts
          command: |
            set -e

            # Workaround old docker images with incorrect $HOME
            # check https://github.com/docker/docker/issues/2968 for details
            if [ "${HOME}" = "/" ]
            then
              export HOME=$(getent passwd $(id -un) | cut -d: -f6)
            fi

            mkdir -p ~/.ssh

            echo '
            github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
            ' >> ~/.ssh/known_hosts
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "package.json" }}
            - dev-dependencies-
      - run: 
          name: Installing dependencies
          command: yarn install --ignore-scripts
      - save_cache:
          paths:
            - node_modules
          key: dev-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  linting:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: Running linter
          command: yarn lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: Setting up CodeClimate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Running unit tests
          command: |
            ./cc-test-reporter before-build
            yarn test-coverage -- --coverageDirectory "./coverage"
            ./cc-test-reporter after-build --coverage-input-type lcov

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Running build
          command: yarn build  
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy-storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploying Storybook to GitHub Pages
          command: yarn deploy-storybook --ci

  cleanup:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Removing dev dependencies
          command: rm -rf node_modules
      - run: 
          name: Installing prod dependencies
          command: yarn install --production --ignore-scripts
      - persist_to_workspace:
          root: .
          paths:
            - node_modules 

workflows:
  version: 2

  acceptance:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - linting:
          filters:
            branches:
              ignore: gh-pages
          requires:
            - setup
      - test:
          filters:
            branches:
              ignore: gh-pages
          requires:
            - setup
      - build:
          filters:
            branches:
              ignore: gh-pages
          requires:
            - setup

  release:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]$/
      - cleanup:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]$/
          requires:
            - build
      - build:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]$/
          requires:
            - setup
      - linting:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]$/
          requires:
            - setup
      - test:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]$/
          requires:
            - setup
      - deploy-storybook:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]$/
          requires:
            - cleanup
            - test
