/// <reference types="styled-components" />
import React from 'react';
import { PropsType as BareButtonPropsType } from '../Button/base';
import ThemeType from '../../types/ThemeType';
import { MediumIcons } from '../Icon/types';
declare type IconButtonThemeType = {
    primary: {
        color: string;
        backgroundColor: string;
    };
    destructive: {
        color: string;
    };
};
declare type PropsType = BareButtonPropsType & {
    theme?: ThemeType;
    icon: keyof typeof MediumIcons;
    variant: 'primary' | 'destructive';
};
declare const _default: React.ForwardRefExoticComponent<Pick<Pick<Pick<BareButtonPropsType & {
    children: JSX.Element;
} & {
    theme?: ThemeType | undefined;
    icon: "archive" | "arrowDownCircle" | "arrowDown" | "arrowLeftCircle" | "arrowLeft" | "arrowRightCircle" | "arrowRight" | "arrowUpCircle" | "ban" | "barChart" | "barcode" | "barsCircle" | "bars" | "bellSlash" | "bell" | "book" | "bookmark" | "bullet" | "bullseye" | "calculator" | "calendar" | "camera" | "caretDown" | "caretLeft" | "caretRight" | "caretUp" | "caretVertical" | "cartArrow" | "cartPlus" | "cart" | "cash" | "ccDinersclub" | "ccMastercard" | "ccVisa" | "certificate" | "checkmarkCircleAlt" | "checkmarkCircle" | "checkmarkSquare" | "checkmark" | "chevronDownCircle" | "chevronDownSquare" | "chevronDown" | "chevronLeftCircle" | "chevronLeftSquare" | "chevronLeft" | "chevronRightCircle" | "chevronRightSquare" | "chevronRight" | "chevronUpCircle" | "chevronUpSquare" | "chevronUp" | "clipboard" | "clock" | "close" | "cloudDownload" | "cloudUpload" | "cloud" | "code" | "comment" | "comments" | "compress" | "copy" | "creditCard" | "crossCircle" | "crosshairs" | "cube" | "cubes" | "dangerCircleAlt" | "dangerCircle" | "dangerTriangleAlt" | "dangerTriangle" | "dashboard" | "desktop" | "download" | "editSquare" | "ellipsisH" | "ellipsisV" | "emptyCircle" | "expandAlt" | "expand" | "externalLinkSquare" | "eyeSlash" | "eye" | "eyedropper" | "facebook" | "fileCode" | "fileExcel" | "fileImage" | "fileMusic" | "filePdf" | "fileText" | "fileVideo" | "fileWord" | "fileZip" | "file" | "film" | "filter" | "flagCheckered" | "flagO" | "flag" | "folderOpen" | "folder" | "frown" | "gear" | "gift" | "globe" | "gridAlt" | "gridView" | "grid" | "handGrab" | "handPointer" | "handStop" | "heartO" | "heart" | "home" | "image" | "inbox" | "infoCircle" | "instagram" | "key" | "keyboard" | "laptop" | "lifeBouy" | "lightbulb" | "lineChart" | "link" | "listAlt" | "listOl" | "list" | "locked" | "mail" | "mapMarker" | "mapSign" | "map" | "meh" | "minusCircle" | "minusSquare" | "minus" | "mobile" | "moveHorizontal" | "moveVertical" | "move" | "newspaper" | "ordersAlt" | "ordersAlt2" | "orders" | "paperclip" | "paste" | "pencil" | "phone" | "pieChart" | "pinterest" | "plug" | "plusCircle" | "plusSquare" | "plus" | "powerOff" | "printer" | "puzzle" | "qrcode" | "questionCircle" | "receipt" | "recycle" | "reload" | "rocket" | "rotateLeft" | "rotateRight" | "search" | "send" | "server" | "shield" | "signIn" | "signOut" | "sitemap" | "sliders" | "smile" | "sortAlphaAsc" | "sortAlphaDesc" | "sortAmountAsc" | "sortAmountDesc" | "sortNumericAsc" | "sortNumericDesc" | "starEmpty" | "starHalfEmpty" | "starHalf" | "star" | "stock" | "store" | "tablet" | "tag" | "tags" | "thumbTack" | "thumbsDown" | "thumbsUp" | "trash" | "truck" | "twitter" | "undo" | "unlink" | "unlocked" | "user" | "users" | "youtube" | "zoomIn" | "zoomOut";
    variant: "primary" | "destructive";
}, "title" | "icon" | "onClick" | "theme" | "className" | "id" | "disabled" | "variant" | "compact" | "target" | "href" | "loading"> & Partial<Pick<BareButtonPropsType & {
    children: JSX.Element;
} & {
    theme?: ThemeType | undefined;
    icon: "archive" | "arrowDownCircle" | "arrowDown" | "arrowLeftCircle" | "arrowLeft" | "arrowRightCircle" | "arrowRight" | "arrowUpCircle" | "ban" | "barChart" | "barcode" | "barsCircle" | "bars" | "bellSlash" | "bell" | "book" | "bookmark" | "bullet" | "bullseye" | "calculator" | "calendar" | "camera" | "caretDown" | "caretLeft" | "caretRight" | "caretUp" | "caretVertical" | "cartArrow" | "cartPlus" | "cart" | "cash" | "ccDinersclub" | "ccMastercard" | "ccVisa" | "certificate" | "checkmarkCircleAlt" | "checkmarkCircle" | "checkmarkSquare" | "checkmark" | "chevronDownCircle" | "chevronDownSquare" | "chevronDown" | "chevronLeftCircle" | "chevronLeftSquare" | "chevronLeft" | "chevronRightCircle" | "chevronRightSquare" | "chevronRight" | "chevronUpCircle" | "chevronUpSquare" | "chevronUp" | "clipboard" | "clock" | "close" | "cloudDownload" | "cloudUpload" | "cloud" | "code" | "comment" | "comments" | "compress" | "copy" | "creditCard" | "crossCircle" | "crosshairs" | "cube" | "cubes" | "dangerCircleAlt" | "dangerCircle" | "dangerTriangleAlt" | "dangerTriangle" | "dashboard" | "desktop" | "download" | "editSquare" | "ellipsisH" | "ellipsisV" | "emptyCircle" | "expandAlt" | "expand" | "externalLinkSquare" | "eyeSlash" | "eye" | "eyedropper" | "facebook" | "fileCode" | "fileExcel" | "fileImage" | "fileMusic" | "filePdf" | "fileText" | "fileVideo" | "fileWord" | "fileZip" | "file" | "film" | "filter" | "flagCheckered" | "flagO" | "flag" | "folderOpen" | "folder" | "frown" | "gear" | "gift" | "globe" | "gridAlt" | "gridView" | "grid" | "handGrab" | "handPointer" | "handStop" | "heartO" | "heart" | "home" | "image" | "inbox" | "infoCircle" | "instagram" | "key" | "keyboard" | "laptop" | "lifeBouy" | "lightbulb" | "lineChart" | "link" | "listAlt" | "listOl" | "list" | "locked" | "mail" | "mapMarker" | "mapSign" | "map" | "meh" | "minusCircle" | "minusSquare" | "minus" | "mobile" | "moveHorizontal" | "moveVertical" | "move" | "newspaper" | "ordersAlt" | "ordersAlt2" | "orders" | "paperclip" | "paste" | "pencil" | "phone" | "pieChart" | "pinterest" | "plug" | "plusCircle" | "plusSquare" | "plus" | "powerOff" | "printer" | "puzzle" | "qrcode" | "questionCircle" | "receipt" | "recycle" | "reload" | "rocket" | "rotateLeft" | "rotateRight" | "search" | "send" | "server" | "shield" | "signIn" | "signOut" | "sitemap" | "sliders" | "smile" | "sortAlphaAsc" | "sortAlphaDesc" | "sortAmountAsc" | "sortAmountDesc" | "sortNumericAsc" | "sortNumericDesc" | "starEmpty" | "starHalfEmpty" | "starHalf" | "star" | "stock" | "store" | "tablet" | "tag" | "tags" | "thumbTack" | "thumbsDown" | "thumbsUp" | "trash" | "truck" | "twitter" | "undo" | "unlink" | "unlocked" | "user" | "users" | "youtube" | "zoomIn" | "zoomOut";
    variant: "primary" | "destructive";
}, "children">>, "children" | "title" | "icon" | "onClick" | "className" | "id" | "disabled" | "variant" | "compact" | "target" | "href" | "loading"> & {
    theme?: ThemeType | undefined;
} & {
    as?: "symbol" | "object" | "code" | "filter" | "image" | "link" | "map" | "title" | React.ComponentClass<any, any> | React.FunctionComponent<any> | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "cite" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "details" | "dfn" | "dialog" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "footer" | "form" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "kbd" | "keygen" | "label" | "legend" | "li" | "main" | "mark" | "menu" | "menuitem" | "meta" | "meter" | "nav" | "noindex" | "noscript" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "progress" | "q" | "rp" | "rt" | "ruby" | "s" | "samp" | "script" | "section" | "select" | "small" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "table" | "tbody" | "td" | "textarea" | "tfoot" | "th" | "thead" | "time" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr" | "webview" | "svg" | "animate" | "animateTransform" | "circle" | "clipPath" | "defs" | "desc" | "ellipse" | "feBlend" | "feColorMatrix" | "feComponentTransfer" | "feComposite" | "feConvolveMatrix" | "feDiffuseLighting" | "feDisplacementMap" | "feDistantLight" | "feFlood" | "feFuncA" | "feFuncB" | "feFuncG" | "feFuncR" | "feGaussianBlur" | "feImage" | "feMerge" | "feMergeNode" | "feMorphology" | "feOffset" | "fePointLight" | "feSpecularLighting" | "feSpotLight" | "feTile" | "feTurbulence" | "foreignObject" | "g" | "line" | "linearGradient" | "marker" | "mask" | "metadata" | "path" | "pattern" | "polygon" | "polyline" | "radialGradient" | "rect" | "stop" | "switch" | "text" | "textPath" | "tspan" | "use" | "view" | undefined;
}, "children" | "title" | "icon" | "onClick" | "className" | "id" | "disabled" | "variant" | "compact" | "target" | "href" | "loading" | "as"> & {
    theme?: any;
}>;
export default _default;
export { PropsType, IconButtonThemeType };
