import { BadgeThemeType } from '../../components/Badge';
import { BreadcrumbsThemeType } from '../../components/Breadcrumbs/style';
import { ButtonThemeType } from '../../components/Button';
import { CheckboxThemeType } from '../../components/Checkbox/style';
import { ContrastThemeType } from '../../components/Contrast/style';
import { FormRowThemeType } from '../../components/FormRow/style';
import { CounterThemeType } from '../../components/Counter';
import { HeadingThemeType } from '../../components/Heading';
import { IconButtonThemeType } from '../../components/IconButton';
import { IllustrationThemeType } from '../../components/Illustration/style';
import { LinkThemeType } from '../../components/Link/style';
import { MessageStreamThemeType } from '../../components/MessageStream/style';
import { ModalThemeType } from '../../components/Modal/style';
import { NativeSelectThemeType } from '../../components/NativeSelect/style';
import { NotificationThemeType } from '../../components/Notification/style';
import { PopoverThemeType } from '../../components/Popover/style';
import { PromotionBadgeThemeType } from '../../components/PromotionBadge';
import { ProgressThemeType } from '../../components/Progress/style';
import { RadioButtonThemeType } from '../../components/RadioButton/style';
import { RaisedThemeType } from '../../components/Raised';
import { RangeThemeType } from '../../components/Range/style';
import { ScrollBoxThemeType } from '../../components/ScrollBox/style';
import { SelectThemeType } from '../../components/Select/style';
import { SkeletonThemeType } from '../../components/Skeleton/style';
import { SliderThemeType } from '../../components/Slider/style';
import { TableThemeType } from '../../components/Table/style';
import { TextAreaThemeType } from '../../components/TextArea/style';
import { TextFieldThemeType } from '../../components/TextField/style';
import { TextThemeType } from '../../components/Text';
import { TextualButtonThemeType } from '../../components/TextualButton';
import { TileThemeType } from '../../components/Tile';
import { ToastThemeType } from '../../components/Toast/style';
import { ToggleThemeType } from '../../components/Toggle/style';
import { TooltipThemeType } from '../../components/Tooltip/style';
import { AccordionThemeType } from '../../components/Accordion/style';
import { CardThemeType } from '../../components/Card/style';

type ThemeType = {
    Accordion: AccordionThemeType;
    Badge: BadgeThemeType;
    Breadcrumbs: BreadcrumbsThemeType;
    Button: ButtonThemeType;
    Card: CardThemeType;
    Checkbox: CheckboxThemeType;
    Contrast: ContrastThemeType;
    FormRow: FormRowThemeType;
    Counter: CounterThemeType;
    Heading: HeadingThemeType;
    IconButton: IconButtonThemeType;
    Illustration: IllustrationThemeType;
    Link: LinkThemeType;
    MessageStream: MessageStreamThemeType;
    Modal: ModalThemeType;
    NativeSelect: NativeSelectThemeType;
    Notification: NotificationThemeType;
    Popover: PopoverThemeType;
    Progress: ProgressThemeType;
    PromotionBadge: PromotionBadgeThemeType;
    RadioButton: RadioButtonThemeType;
    Raised: RaisedThemeType;
    Range: RangeThemeType;
    ScrollBox: ScrollBoxThemeType;
    Select: SelectThemeType;
    Skeleton: SkeletonThemeType;
    Slider: SliderThemeType;
    Table: TableThemeType;
    Text: TextThemeType;
    TextArea: TextAreaThemeType;
    TextField: TextFieldThemeType;
    TextualButton: TextualButtonThemeType;
    Tile: TileThemeType;
    Toast: ToastThemeType;
    Toggle: ToggleThemeType;
    Tooltip: TooltipThemeType;
};

export default ThemeType;
