name: Deploy
on:
  push:
    # branches:
    #   - master


jobs:
  deploy-site:
    if: github.actor != 'myonlinestore-ci-eu'
    runs-on: ubuntu-latest
    steps:
    - name: Checking out git repository
      uses: actions/checkout@v2-beta
    - name: Setting up Node environment
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Hydrating cache 
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Building bricks
      run: yarn build
    - name: Installing dependencies
      run: cd docs && yarn --frozen-lockfile
    - name: Building site
      run: yarn build
    - name: Static export
      run: yarn export-to-ghpages
    - name: Deploy to github
      uses: peaceiris/actions-gh-pages@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/dist/
      with:
        username: "myonlinestore-ci-eu"
        useremail: "team-tech+myonlinestore-ci-eu@myonlinestore.com"
